name: Cleanup

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:    

jobs:
  cleanup-releases:
    runs-on: ubuntu-24.04
    permissions: 
      contents: write
    steps:
      - name: Delete old releases
        uses: actions/github-script@v7
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });

            const keep = 5; // 保留最新5个
            const cutoffDays = 30; // 删除超过30天的
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - cutoffDays);

            for (const release of releases.slice(keep)) {
              if (new Date(release.created_at) < cutoffDate) {
                // 先删 Release
                await github.rest.repos.deleteRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: release.id
                });
                console.log(`Deleted release: ${release.name}`);

                // 再删对应的 Tag（注意 refs/tags/ 前缀）
                try {
                  await github.rest.git.deleteRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `tags/${release.tag_name}`
                  });
                  console.log(`Deleted tag: ${release.tag_name}`);
                } catch (e) {
                  console.log(`Tag not found or already deleted: ${release.tag_name}`);
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
